// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://cmrlbswsswtprqqgavgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtcmxic3dzc3d0cHJxcWdhdmd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MzAxODgsImV4cCI6MjA3MDIwNjE4OH0.Q0sBLi_YP0m5J51qIV4UWHU8vVpZWAxReEn1JbltH_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);